/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import * as React from 'react';

import { IHeroData } from './hero.data';
import { IHeroProps } from './hero.props.autogenerated';

export interface IHeroViewProps extends IHeroProps<IHeroData> {

}

/**
 *
 * Hero component
 * @extends {React.PureComponent<IHeroProps<IHeroData>>}
 */
class Hero extends React.PureComponent<IHeroProps<IHeroData>> {
    public render(): JSX.Element | null {

        return this.props.renderView(this.props);
    }
}

export default Hero;
