/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import * as React from 'react';

import { IVideolistData } from './videolist.data';
import { IVideolistProps } from './videolist.props.autogenerated';

export interface IVideolistViewProps extends IVideolistProps<IVideolistData> {

}

/**
 *
 * Videolist component
 * @extends {React.PureComponent<IVideolistProps<IVideolistData>>}
 */
class Videolist extends React.PureComponent<IVideolistProps<IVideolistData>> {
    public render(): JSX.Element | null {

        return this.props.renderView(this.props);
    }
}

export default Videolist;
